/* Auto-generated by cbindgen. Do not edit. */

#ifndef MINIFB_FFI_H
#define MINIFB_FFI_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/*
 Opaque window handle
 */
typedef struct MiniFBWindow MiniFBWindow;

/*
 Window creation options
 */
typedef struct MiniFBWindowOptions {
  bool borderless;
  bool title;
  bool resize;
  bool topmost;
  bool transparency;
} MiniFBWindowOptions;

/*
 Create default window options
 */
struct MiniFBWindowOptions minifb_window_options_default(void);

/*
 Create a new window

 # Safety
 - `name` must be a valid null-terminated C string
 - `opts` must be a valid pointer to MiniFBWindowOptions

 Returns null on failure
 */
struct MiniFBWindow *minifb_window_new(const char *name,
                                       uintptr_t width,
                                       uintptr_t height,
                                       const struct MiniFBWindowOptions *opts);

/*
 Free a window

 # Safety
 - `window` must be a valid pointer returned by `minifb_window_new`, or null
 - After calling this function, the pointer is invalid and must not be used
 */
void minifb_window_free(struct MiniFBWindow *window);

/*
 Check if window is still open

 # Safety
 - `window` must be a valid pointer returned by `minifb_window_new`
 */
bool minifb_window_is_open(const struct MiniFBWindow *window);

/*
 Update the window (process events, no buffer update)

 # Safety
 - `window` must be a valid pointer returned by `minifb_window_new`
 */
void minifb_window_update(struct MiniFBWindow *window);

/*
 Update the window with a pixel buffer

 # Safety
 - `window` must be a valid pointer returned by `minifb_window_new`
 - `buffer` must point to at least `width * height` u32 values

 Returns 0 on success, -1 on error
 */
int32_t minifb_window_update_with_buffer(struct MiniFBWindow *window,
                                         const uint32_t *buffer,
                                         uintptr_t width,
                                         uintptr_t height);

/*
 Get the window size

 # Safety
 - `window` must be a valid pointer returned by `minifb_window_new`
 - `out_width` and `out_height` must be valid pointers
 */
void minifb_window_get_size(const struct MiniFBWindow *window,
                            uintptr_t *out_width,
                            uintptr_t *out_height);

/*
 Set the window title

 # Safety
 - `window` must be a valid pointer returned by `minifb_window_new`
 - `title` must be a valid null-terminated C string
 */
void minifb_window_set_title(struct MiniFBWindow *window, const char *title);

/*
 Set target FPS (limits update rate)

 # Safety
 - `window` must be a valid pointer returned by `minifb_window_new`
 */
void minifb_window_set_target_fps(struct MiniFBWindow *window, uintptr_t fps);

/*
 Set background color (RGB, 0-255 each)

 # Safety
 - `window` must be a valid pointer returned by `minifb_window_new`
 */
void minifb_window_set_background_color(struct MiniFBWindow *window,
                                        uint8_t red,
                                        uint8_t green,
                                        uint8_t blue);

#endif  /* MINIFB_FFI_H */
