
surface_net.o : surface_net.c
	gcc -Wall -O3 -O -c surface_net.c -lm

marching_squares.o : marching_squares.c
	gcc -Wall -O3 -O -c marching_squares.c -lm

default: surface_net.o marching_squares.o

.DEFAULT_GOAL := default
